### ISSUE TITLE
Too many import statements

### ISSUE THREAD

**Issue by o-t-w** [springernature/frontend-global-toolkit#57]
IMO it would be simpler and easier to have all the sass for a component in a single folder. Even for a larger component with a larger amount of CSS, I'd find this a lot easier to work. For smaller components, some files will have literally a couple of lines of code. I already need to split my editor into multiple panes to deal with markup, css and javascript at the same time, needing to do so just to write some styles seems overkill 😓
The structure is based on the Harry Roberts ITCSS folder structure, but I think he was talking about how to structure a whole CSS codebase, not a small discrete component.

**Comment by jpw** [comment]
Seems to not be the consensus.
