### ISSUE TITLE
Do we need `global-colours` as well as `global-css-base` ?

### ISSUE THREAD

**Issue by jpw** [springernature/frontend-global-toolkit#85]
Right now we have `global-colours` which is in effect an abstract bag of variable names to be overridden at a brand instance, when actually implemented.

Was just chatting with @o-t-w and we were wondering if it is worth having this as separate package?

In [this PR](https://github.com/springernature/frontend-global-toolkit/pull/84) we are considering the base styles for element selectors (e.g. `body`) in the `global-css-base`. In `global-css-base` am guessing we want to set a `color` property on the `body` too. This means having colours as a dep, `@import`ing the colours and using the variable in the `body { color:` definition.

So I am proposing merging the colour variable definitions into `global-css-base`.  A user will typically want the `global-css-base` for their brand and I don't think it's unreasonable for this to include colours, as the purpose of the package is to define to base CSS context for a brand, colours and all.

**Comment by jpw** [comment]
Hmm am not sure about this, let's have a play with the code and see what we think.

**Comment by o-t-w** [comment]
Springer Open is one example where somebody would want the fonts and colours, but maybe not the `global-css-base` styles?

**Comment by jpw** [comment]
> Springer Open is one example where somebody would want the fonts and colours, but maybe not the global-css-base styles?

That's maybe a possibility. How I thought this might _usually_ work is, rather than having colours etc a dependency of client apps, we could make them dependencies of the brand base package (which makes sense) and client apps would just have that as a dependency. Having them separate would allow for more flexibility though. Not sure how this would work exactly though, would like some input from @alexkilgour ...

**Comment by o-t-w** [comment]
What I've gone for with Springer https://github.com/springernature/frontend-springer-toolkit

**Comment by jpw** [comment]
Colours now live in the brand packages settings files. [Example for Nature](https://github.com/springernature/frontend-nature-toolkit/blob/master/packages/nature-context/scss/10-settings/colors.scss).
